/// <reference path="@flyde/runtime/index.d.ts" />

/*
    This file is generated by flyde-cli. Please do not edit it.
*/

declare module '@flyde/runtime' {

    // generated flow typings
    export function executeFlow(path: 'Bob1.flyde', args: {}): Promise<any>;
    export function executeFlow(path: 'ApisCombination.flyde', args: {}): Promise<any>;
    export function executeFlow(path: 'debounce-throttle.flyde', args: {}): Promise<any>;
    export function executeFlow(path: 'fibonacci.flyde', args: {}): Promise<any>;
    export function executeFlow(path: 'hello-world.flyde', args: {}): Promise<any>;
    export function executeFlow(path: 'react-counter.flyde', args: {}): Promise<any>;
}
